### ISSUE TITLE
[Bug] Demo showing code incorrectly on Chrome

### ISSUE THREAD

**Issue by sskieller** [huntercfreeman/Blazor.Text.Editor#24]
Hello, tested your demo on https://hunter-freeman-dev.azurewebsites.net/csharp in Chrome

And the code is showing wrongly indented into the wall:
![image](https://user-images.githubusercontent.com/11709063/206993531-8fc37547-a48b-4fd6-b475-52204056eb84.png)

**Comment by sskieller** [comment]
This happens on all the language demoes

**Comment by huntercfreeman** [comment]
I have seen weird behavior from the gutter. The image you show has the text almost having a higher z-index as it is above the gutter. I haven't seen this yet thanks for making an issue.

Going to look into this.

**Comment by sskieller** [comment]
This happens on both my pc's :s

**Comment by huntercfreeman** [comment]
I have updated the Demo to v6.0.0 and in this update I made a massive effort to fix bugs relating to the gutter (line numbers).

If you have the time please let me know if this issue is still occurring for you.

Demo website: (Clear your cache if you see an older version as the site uses WebAssembly)

https://hunter-freeman-dev.azurewebsites.net/

**Comment by huntercfreeman** [comment]
Today v6.1.0 was published. All gutter css styling bugs were looked at and should be fixed now. If this is not the case please open another issue.
